version: '3.7'

services:
  nextcloud:
    image: nextcloud:14.0.3-apache
    env_file:
      .env
    links:
      - db
    depends_on:
      - db
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
  
  db:
    image: mysql:8.0.13
    restart: always
    env_file:
      .env
    networks:
      default:
        aliases:
          - mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
      
  ngnix:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - nextcloud

volumes:
  nextcloud:
  mysql:

